name: Release

on:
  push:
    branches:
      - main  # Trigger on every push to main branch

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install Command Line Tools
      run: |
        sudo xcode-select --install || true
        
    - name: Build DMG
      run: |
        make release
        
    - name: Get version info
      id: get_version
      run: |
        # Get version from Info.plist
        VERSION=$(defaults read "$GITHUB_WORKSPACE/KollektivWidget/Info.plist" CFBundleShortVersionString)
        BUILD=$(git rev-list --count HEAD)
        COMMIT_SHORT=$(git rev-parse --short HEAD)
        
        # Create a unique version with build number
        FULL_VERSION="${VERSION}.${BUILD}"
        
        echo "VERSION=${FULL_VERSION}" >> $GITHUB_OUTPUT
        echo "BASE_VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "BUILD_NUMBER=${BUILD}" >> $GITHUB_OUTPUT
        echo "COMMIT_SHORT=${COMMIT_SHORT}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        release_name: KollektivWidget v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## KollektivWidget v${{ steps.get_version.outputs.VERSION }}
          
          **Build #${{ steps.get_version.outputs.BUILD_NUMBER }}** (commit: ${{ steps.get_version.outputs.COMMIT_SHORT }})
          
          A macOS menu bar app for Norwegian public transport departures.
          
          ### Installation
          1. Download the DMG file below
          2. Open the DMG and drag KollektivWidget.app to Applications
          3. Launch from Applications folder
          4. Grant notification permissions when prompted
          
          ### Features
          - Real-time departure information for all Norwegian public transport
          - Customizable notification timing
          - Dark mode support
          - Menu bar integration
          
          ### System Requirements
          - macOS 13.0 or later
          - Internet connection for real-time data
          
          ---
          *This release was automatically generated from the latest commit on main.*
          
        draft: false
        prerelease: false
        
    - name: Upload DMG Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/KollektivWidget.dmg
        asset_name: KollektivWidget-v${{ steps.get_version.outputs.VERSION }}.dmg
        asset_content_type: application/octet-stream
